shop/blog/urls.py
from django.urls import path, re_path, register_converter
from . import views

from extensions import converters

register_converter(converters.fourDigitYear, 'yyyy')

app_name = "blog"
urlpatterns = [

    # ex: hostname/blog
    path('', views.index, name = 'index'),

    # ex: hostname/blog/1
    path('<int:post_id>', views.detail, name = 'detail'),

    # ex: hostname/blog/archive/2018
    #path('archive/<int:year>/', views.archiveYear, name = 'archive'),
    path('archive/<yyyy:year>/', views.archiveYear, name = 'archive'),
    #re_path(r'^archive/(?p<year>[0-9]{4})/$', views.archiveYear, name = 'archive'),      # using re_path
]

shop/shop/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'blog/', include('blog.urls')),
]

shop/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):   # Model name is post

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length = 60)
    slug = models.SlugField(max_length = 100)
    body = models.TextField()
    published = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 60, choices = STATUS_CHOICES, default = 'draft')

shop/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import Http404
from .models import Post
from django.views.decorators.http import require_http_methods, require_GET, require_safe


@require_http_methods(["GET"])
def index(request):
    latest_post_list = Post.objects.order_by('-published')[:5]
    context = { 'latest_post_list' : latest_post_list }
    return render(request, 'index.html', context)

@require_GET
def detail(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    context = { 'post' : post }
    return render(request, 'detail.html', context)

@require_safe
def archiveYear(request, year):

    year_archive_post = get_list_or_404(Post, published__year = year)    # instead of Post.objects.filter(published__year = year)
    context = { 'year_archive_post' : year_archive_post }
    return render(request, 'archive.html', context)

shop/blog/templates/archive.html
{% extends "parent/main.html" %}

{% block title %}
  archive
{% endblock %}

{% block body %}
  {% if year_archive_post %}
    {% for post in year_archive_post %}
      {{ post.title }}
    {% endfor %}
  {% else %}
    <p>no post are available</p>
  {% endif %}
{% endblock %}

shop/blog/templates/detail.html
{% extends "parent/main.html" %}

{% block title %}
details
{% endblock %}

{% block body %}
    <h1>this is out post:</h1>
    <h2>post slug : {{ post.slug }}</h2>
    <h3>post body : {{ post.body }}</h3>
{% endblock %}

shop/blog/templates/index.html
{% extends "parent/main.html" %}

{% block title %}
  main page
{% endblock %}

{% block body %}

  {% include "partials/carosel.html" %}

  <h1>All posts</h1>
  {% if latest_post_list  %}
    <ul>
      {% for post in latest_post_list %}
        <li><a href="{% url 'blog:detail' post.id %}">{{ post.slug }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p style="color:tomato;">No post available</p>
  {% endif %}
{% endblock %}

shop/blog/templates/parent/main.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>
    {% include "partials/header.html" %}
    {% include "partials/nav.html" %}

    <div class="container-fluid">

      {% block body %}

      {% endblock %}

    </div>

    {% include "partials/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script type="{% static 'js/main.js' %}"></script>
  </body>
</html>

shop/blog/templates/partials/carosel.html
<div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="la.jpg" alt="Los Angeles">
    </div>
    <div class="carousel-item">
      <img src="chicago.jpg" alt="Chicago">
    </div>
    <div class="carousel-item">
      <img src="ny.jpg" alt="New York">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>

shop/blog/templates/partials/nav.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

<!-- Links -->
 <ul class="navbar-nav">
   <li class="nav-item">
     <a class="nav-link" href="#">Link 1</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="#">Link 2</a>
   </li>
 </ul>

 <!-- Navbar text-->
 <span class="navbar-text">
   Navbar text
 </span>

</nav> 